apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moon-bot

resources:
  - ../namespace.yaml
  - ../serviceaccount.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: moon-bot

images:
  - name: moon-bot
    newName: ghcr.io/YOUR_ORG/moon-bot
    newTag: latest
