apiVersion: v1
kind: Service
metadata:
  name: moon-bot-github-only
  namespace: moon-bot
  labels:
    app.kubernetes.io/name: moon-bot
    app.kubernetes.io/component: github-bot-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: moon-bot
    app.kubernetes.io/component: github-bot
  ports:
    - name: webhook
      port: 3000
      targetPort: webhook
