apiVersion: v1
kind: ServiceAccount
metadata:
  name: moon-bot
  namespace: moon-bot
  labels:
    app.kubernetes.io/name: moon-bot
    app.kubernetes.io/component: rbac
automountServiceAccountToken: false
